version: '2'
services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile-gpu
    volumes:
      - .:/srv
      - ./spacy:/usr/local/lib/python3.5/dist-packages/en_vectors_web_lg
    ports:
      - 8888:8888